### ISSUE TITLE
Connection refused from php SDK 

### ISSUE THREAD

**Issue by flik** [minio/cookbook#237]
url in browser is working: http://localhost:9004/minio/

BUT when I try to connect by code it is giving error :
```

! )  Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with  message 'Error executing "CreateBucket" on  "http://localhost:9004/testbucket"; AWS HTTP error: cURL error 7: Failed  to connect to localhost port 9004: Connection refused (see  http://curl.haxx.se/libcurl/c/libcurl-errors.html)'  GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect  to localhost port 9004: Connection refused (see  http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/public/v2/upload/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 191
--
```

**code**: 
```
date_default_timezone_set('America/Los_Angeles');
require 'vendor/autoload.php';

$s3 = new Aws\S3\S3Client([
    'version' => 'latest',
    'region'  => 'us-east-1',
    'endpoint' => 'http://localhost:9004/minio/',
    'use_path_style_endpoint' => true,
    'credentials' => [
            'key'    => 'AKIAIOSFODNN7EXAMPLE',
            'secret' => 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
        ],
]);


$bucket = 'testbucket';

// Create a bucket
$result = $s3->createBucket([
    'Bucket' => $bucket,
]);

```

**docker-compose**:
```
minio1:
      container_name: minio1
      image: minio/minio:RELEASE.2018-11-06T01-01-02Z
      hostname: minio1
      volumes:
        - minio1-data:/export
      ports:
        - "9004:9000"
      networks:
        - webnet
      environment:
        MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
        MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      deploy:
       restart_policy:
         delay: 10s
         max_attempts: 10
         window: 60s
       placement:
         constraints:
           - node.labels.minio1==true
      command: minio server /data
```
